#!/usr/bin/env bash
#
# Postprocess scaffold
#

#
# These are basics for ramverk1-me
#
composer install
make cimage-update

#
# These are specifics for upgrading to Anax DI
#
#cp vendor/anax/di/config/di.php config/
cp vendor/anax/di/src/App/AppDI.php src/App
cp vendor/anax/di/src/App/AppDIMagic.php src/App

#
# These are specifics for upgrading to Anax DI with router config
#
#rsync -av vendor/anax/router/config/{route2.php,route2} config/
rsync -av vendor/anax/router/config/route2 config/

#
# These are specifics for upgrading to Anax database with User
#
rsync -av vendor/anax/database/sql/ sql/

# Create the SQLite database with the table User
sqlite3 data/db.sqlite < sql/ddl/user_sqlite.sql
chmod 777 data
chmod 666 data/db.sqlite
