#!/usr/bin/env bash
#
# Postprocess scaffold
#

#
# Read input from user supporting a default value for reponse.
# arg1: The message to display.
# arg2: The default value.
#
input()
{
    read -r -p "$1 [$2]: "
    echo "${REPLY:-$2}"
}



#
# Compatible sed -i.
# https://stackoverflow.com/a/4247319/341137
# arg1: Expression.
# arg2: Filename.
#
sedi()
{
    sed -i.bak "$1" "$2"
    rm -f "$2.bak"
}



#
# Read values from user input
#
NAMESPACE=$( input "Namespace" "${ANAX_NAMESPACE:-Anax\\\\XXX}" )
CLASSNAME=$( input "Class name" "ClassName" )
cLASSNAME=${CLASSNAME,}

# Model
file="MODEL.php"
sedi "s/NAMESPACE/$NAMESPACE/g" "$file"
sedi "s/CLASSNAME/$CLASSNAME/g" "$file"
mv "$file" "$CLASSNAME.php"

# Controller
file="CONTROLLER.php"
sedi "s/NAMESPACE/$NAMESPACE/g" "$file"
sedi "s/CLASSNAME/$CLASSNAME/g" "$file"
mv "$file" "${CLASSNAME}Controller.php"

# Routes for the controller
path="extra/config/route"
file="CONTROLLER.php"
sedi "s/cLASSNAME/$cLASSNAME/g" "$path/$file"
mv "$path/$file" "$path/${cLASSNAME}Controller.php"

# To add the router file
file="extra/config/route.php"
sedi "s/cLASSNAME/$cLASSNAME/g" "$file"

# To add controller as service
file="extra/config/di.php"
sedi "s/NAMESPACE/$NAMESPACE/g" "$file"
sedi "s/CLASSNAME/$CLASSNAME/g" "$file"
sedi "s/cLASSNAME/$cLASSNAME/g" "$file"

# Prepare database table MySQL
path="extra/sql/ddl"
file="mysql.sql"
sedi "s/CLASSNAME/$CLASSNAME/g" "$file"
mv "$path/$file" "$path/${cLASSNAME}_$file"

# Prepare database table SQLite
path="extra/sql/ddl"
file="sqlite.sql"
sedi "s/CLASSNAME/$CLASSNAME/g" "$file"
mv "$path/$file" "$path/${cLASSNAME}_$file"
